### ISSUE TITLE
服务器server端 和   worker执行器端 总是会莫名其妙的挂掉

### ISSUE THREAD

**Issue by ltcyxgithub** [PowerJob/Official-Website#1]
上周五部署在服务器daun的server     和worker   在周六的时候就挂掉了     不超过一天  时间      就自己挂掉了  。刚部署上去是好的   一直都这样        

![8a73bb11f8482cc54e4c77be40ddb3b](https://user-images.githubusercontent.com/77946924/105653183-1b6c9a00-5ef6-11eb-8e4d-297e17b11d87.png)

**Comment by KFCFans** [comment]
worker 的版本是什么？
网络情况和机器配置大概如何？

这个问题现在确实挺离奇的...

**Comment by ltcyxgithub** [comment]
服务器  一直没问题的    部署的有其他的项目一直运行稳定的   ，是不是宕机问题 不止我这出现   大部分都遇到了吗 ，希望都研究下吧    项目周期快结束了

**Comment by ltcyxgithub** [comment]
worker  用的版本 是20年十一之前的版本

**Comment by KFCFans** [comment]
发worker版本号

**Comment by ltcyxgithub** [comment]
wokrer  版本号在哪看 呀   当时只记得down代码了

**Comment by KFCFans** [comment]
看 pom 版本。

应该是有内存泄漏问题的版本，升级到最新版本吧。

**Comment by ltcyxgithub** [comment]
4.0版本的

**Comment by KFCFans** [comment]
...
没有 4.0 这个版本


你就升级到最新版本解决吧。
